name: huggingface
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  empty_widget: ^0.0.5
  
  flutter_linkify: ^6.0.0
  http: ^1.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  loader_overlay: ^4.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  url_launcher: ^6.2.5
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/data.json
    - assets/samples/apple/
    - assets/samples/banana/
    - assets/samples/mango/
